-- Phase 4: Hibernate Envers audit trail.
-- Custom revinfo carries who made the change (JWT email / id, or "system" for bootstrap/jobs).

create table revinfo (
    rev         integer generated by default as identity primary key,
    revtstmp    bigint       not null,
    changed_by  varchar(255) not null
);

-- Employee history: salary, title, manager, status, role, department, and the other
-- non-secret columns. password_hash / must_change_password / version are not audited.
create table employees_aud (
    id                   uuid         not null,
    rev                  integer      not null references revinfo (rev),
    revtype              smallint     not null,
    employee_number      varchar(20),
    full_name            varchar(150),
    email                varchar(255),
    role                 varchar(20),
    job_title            varchar(120),
    department_id        uuid,
    manager_id           uuid,
    hire_date            date,
    salary               numeric(12, 2),
    status               varchar(20),
    terminated_at        date,
    created_at           timestamptz,
    updated_at           timestamptz,
    primary key (id, rev)
);

create index employees_aud_id_rev_idx on employees_aud (id, rev desc);

-- Leave-request decisions (status / decided_by / decided_at / decision_note).
create table leave_requests_aud (
    id            uuid        not null,
    rev           integer     not null references revinfo (rev),
    revtype       smallint    not null,
    employee_id   uuid,
    leave_type    varchar(20),
    start_date    date,
    end_date      date,
    leave_year    integer,
    working_days  integer,
    reason        varchar(500),
    status        varchar(20),
    decided_by    uuid,
    decided_at    timestamptz,
    decision_note varchar(500),
    created_at    timestamptz,
    updated_at    timestamptz,
    primary key (id, rev)
);

-- Payroll-run finalization (and creation) history.
create table payroll_runs_aud (
    id           uuid        not null,
    rev          integer     not null references revinfo (rev),
    revtype      smallint    not null,
    run_year     integer,
    run_month    integer,
    status       varchar(20),
    created_by   uuid,
    created_at   timestamptz,
    finalized_by uuid,
    finalized_at timestamptz,
    primary key (id, rev)
);
